name = "WERX"
license = "ISC" # Pre-2007 ISC license
licenselink = "https://github.com/xplshn/werx/blob/master/LICENSE.ISC"
description = "A complete rewrite of hugo-werx, a 1:1 replica of the style of cat-v.org|werc.cat-v.org"
homepage = "https://xplshn.github.io/werx"
tags = ["minimal", "blog", "documentation", "personal", "simple", "clean", "minimalist", "suckless", "vanilla html", "vanilla css"]
features = ["blog", "docs"]
min_version = "0.80.0"

[author]
  author = "xplshn"
  homepage = "https://xplshn.github.io/werx"
  repo = "https://github.com/xplshn/hugo-werx"
